#PBS -N mpi_barrier_7
#PBS -l nodes=1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=00:05:00
#PBS -q coc-ice
#PBS -j oe
#PBS -o mpi_7.out

export MPI_NUM_PROCS=7
echo "Started on `/bin/hostname`"
echo "Nodes chosen are:"
cat $PBS_NODEFILE

cd ~/shruti/AOS-Project2/mpi

module load gcc/8.3.0 mvapich2/2.3.2

make clean
make all

echo "MCS Tree barrier"
mpirun -np 7 ./mpi1 7

sleep 4
echo "Dissemination barrier"
mpirun -np 7 ./mpi2 7